#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Volumes/HDD/developer/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/user/Downloads/plugins-main/packages/webview_flutter/webview_flutter/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/user/Downloads/plugins-main/packages/webview_flutter/webview_flutter/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.2.2"
export "FLUTTER_BUILD_NUMBER=3"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/user/Downloads/plugins-main/packages/webview_flutter/webview_flutter/example/.dart_tool/package_config.json"
